Wed, 09 Mar 2022 21:46:15-root-logger_handler.py-[line:129]-ERROR-[日志信息]: 用例执行失败：assert '登录成功' == '用户名不存在'
Wed, 09 Mar 2022 21:46:17-root-logger_handler.py-[line:129]-ERROR-[日志信息]: 用例执行失败：assert '登录成功' == '用户名不存在'
Wed, 09 Mar 2022 21:47:40-root-logger_handler.py-[line:129]-ERROR-[日志信息]: 用例执行失败：assert '登录成功' == '用户名不存在'
Wed, 09 Mar 2022 21:47:42-root-logger_handler.py-[line:129]-ERROR-[日志信息]: 用例执行失败：assert '登录成功' == '用户名不存在'
Wed, 09 Mar 2022 21:48:39-root-logger_handler.py-[line:129]-ERROR-[日志信息]: 用例执行失败：assert '登录成功' == '用户名不存在'
Wed, 09 Mar 2022 21:48:41-root-logger_handler.py-[line:129]-ERROR-[日志信息]: 用例执行失败：assert '登录成功' == '用户名不存在'
Wed, 09 Mar 2022 21:50:43-root-logger_handler.py-[line:129]-ERROR-[日志信息]: 用例执行失败：assert '登录成功' == '用户名不存在'
Wed, 09 Mar 2022 21:50:45-root-logger_handler.py-[line:129]-ERROR-[日志信息]: 用例执行失败：assert '登录成功' == '用户名不存在'
Wed, 09 Mar 2022 21:50:48-root-logger_handler.py-[line:129]-ERROR-[日志信息]: 用例执行失败：assert '注册成功' == '用户名已经存在'
Wed, 09 Mar 2022 21:50:50-root-logger_handler.py-[line:129]-ERROR-[日志信息]: 用例执行失败：assert '注册成功' == '用户名已经存在'
Wed, 09 Mar 2022 21:50:52-root-logger_handler.py-[line:129]-ERROR-[日志信息]: 用例执行失败：assert '注册成功' == '用户名已经存在'
Wed, 09 Mar 2022 21:50:54-root-logger_handler.py-[line:129]-ERROR-[日志信息]: 用例执行失败：assert '注册成功' == '用户名已经存在'
